config/routes.rb
Rails.application.routes.draw do
  resources :fuel_prices

 
    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  #devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  #root "pages#home"
 root "messages#home2"

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  #get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  #get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  #get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  get 'contact', to: 'messages#new', as: :contact
  get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  #get 'visit-simplifly', to: 'messages#location', as: :location
  #get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  #get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  #get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  #get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  get 'testing', to: 'pages#service1'
  #get 'stratus-finance', to: 'pages#stratus', as: :stratus
  #get 'meritize', to: 'pages#meritize', as: :meritize
  #get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  #get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  #get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  #get 'financing', to: 'pages#financing', as: :financing
  #get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  #get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  #get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  #get 'multi-engine-rating', to: 'pages#multi', as: :multi
  #get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  #get 'instrument-rating', to: 'pages#instrument', as: :instrument
  #get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  get 'pilot_tech', to: 'pages#pilot_tech', as: :pilot_tech
  #get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  #get 'our-team', to: 'pages#our_team', as: :our_team
  #get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  #get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  get 'about_us', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  get 'services', to: 'pages#services', as: :services
  get 'contact-us', to: 'pages#contact_us', as: :contact_us

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  #get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  #get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  get 'news_events', to: 'pages#news_events'
  #get 'timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/models/fuel_price.rb
class FuelPrice < ApplicationRecord
end

app/controllers/fuel_prices_controller.rb
class FuelPricesController < ApplicationController
  before_action :set_fuel_price, only: %i[ show edit update destroy ]

  # GET /fuel_prices or /fuel_prices.json
  def index
    @fuel_prices = FuelPrice.all
  end

  # GET /fuel_prices/1 or /fuel_prices/1.json
  def show
  end

  # GET /fuel_prices/new
  def new
    @fuel_price = FuelPrice.new
  end

  # GET /fuel_prices/1/edit
  def edit
  end

  # POST /fuel_prices or /fuel_prices.json
  def create
    @fuel_price = FuelPrice.new(fuel_price_params)

    respond_to do |format|
      if @fuel_price.save
        format.html { redirect_to fuel_price_url(@fuel_price), notice: "Fuel price was successfully created." }
        format.json { render :show, status: :created, location: @fuel_price }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fuel_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_prices/1 or /fuel_prices/1.json
  def update
    respond_to do |format|
      if @fuel_price.update(fuel_price_params)
        format.html { redirect_to fuel_price_url(@fuel_price), notice: "Fuel price was successfully updated." }
        format.json { render :show, status: :ok, location: @fuel_price }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fuel_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_prices/1 or /fuel_prices/1.json
  def destroy
    @fuel_price.destroy

    respond_to do |format|
      format.html { redirect_to fuel_prices_url, notice: "Fuel price was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_price
      @fuel_price = FuelPrice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fuel_price_params
      params.require(:fuel_price).permit(:jet_a_self_service, :jet_a_full_service, :ll_self_service, :ll_full_service)
    end
end

app/helpers/fuel_prices_helper.rb
module FuelPricesHelper
end

app/views/fuel_prices/_form.html.erb
<%= form_with(model: fuel_price, class: "contents") do |form| %>
  <% if fuel_price.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(fuel_price.errors.count, "error") %> prohibited this fuel_price from being saved:</h2>

      <ul>
        <% fuel_price.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :jet_a_self_service %>
    <%= form.text_field :jet_a_self_service, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :jet_a_full_service %>
    <%= form.text_field :jet_a_full_service, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ll_self_service %>
    <%= form.text_field :ll_self_service, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ll_full_service %>
    <%= form.text_field :ll_full_service, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/fuel_prices/_fuel_price.html.erb
<div id="<%= dom_id fuel_price %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Jet a self service:</strong>
    <%= fuel_price.jet_a_self_service %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Jet a full service:</strong>
    <%= fuel_price.jet_a_full_service %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ll self service:</strong>
    <%= fuel_price.ll_self_service %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ll full service:</strong>
    <%= fuel_price.ll_full_service %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this fuel price", fuel_price, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this fuel price', edit_fuel_price_path(fuel_price), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/fuel_prices/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing fuel price</h1>

  <%= render "form", fuel_price: @fuel_price %>

  <%= link_to "Show this fuel price", @fuel_price, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to fuel prices", fuel_prices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fuel_prices/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Fuel prices</h1>
    <%= link_to 'New fuel price', new_fuel_price_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="fuel_prices" class="min-w-full">
    <%= render @fuel_prices %>
  </div>
</div>

app/views/fuel_prices/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New fuel price</h1>

  <%= render "form", fuel_price: @fuel_price %>

  <%= link_to 'Back to fuel prices', fuel_prices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fuel_prices/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @fuel_price %>

    <%= link_to 'Edit this fuel_price', edit_fuel_price_path(@fuel_price), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this fuel_price', fuel_price_path(@fuel_price), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to fuel_prices', fuel_prices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>