config/routes.rb
Rails.application.routes.draw do
  resources :fuel_prices

 
    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  #devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  #root "pages#home"
 root "messages#home2"

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  #get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  #get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  #get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  get 'contact', to: 'messages#new', as: :contact
  get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  #get 'visit-simplifly', to: 'messages#location', as: :location
  #get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  #get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  #get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  #get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  get 'testing', to: 'pages#service1'
  #get 'stratus-finance', to: 'pages#stratus', as: :stratus
  #get 'meritize', to: 'pages#meritize', as: :meritize
  #get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  #get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  #get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  #get 'financing', to: 'pages#financing', as: :financing
  #get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  #get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  #get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  #get 'multi-engine-rating', to: 'pages#multi', as: :multi
  #get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  #get 'instrument-rating', to: 'pages#instrument', as: :instrument
  #get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  get 'pilot_tech', to: 'pages#pilot_tech', as: :pilot_tech
  #get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  #get 'our-team', to: 'pages#our_team', as: :our_team
  #get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  #get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  get 'about_us', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  get 'services', to: 'pages#services', as: :services
  get 'contact-us', to: 'pages#contact_us', as: :contact_us

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  #get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  #get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  get 'news_events', to: 'pages#news_events'
  #get 'timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/models/message.rb
class Message < ApplicationRecord
  before_validation :strip_phone_number
  #after_save :to_lacrm
  
  validates :name, presence: true
  validates :body, presence: { message: "Tell us how we can help" }
  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "must be a valid 10-digit phone number" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }

  def strip_phone_number
    self.phone = phone.to_s.gsub(/[-() ]/, "")
  end

  def to_lacrm
    api_key = ENV['LACRM_API']
    # Set the endpoint and headers
    endpoint = "https://api.lessannoyingcrm.com/v2/"
    headers = {
      "Authorization" => api_key,
      "Content-Type" => "application/json"
    }
    # Get the user ID
    user_payload = {
      "Function" => "GetUser",
      "Parameters" => {}
    }
    user_response = HTTParty.get(endpoint, headers: headers, body: user_payload.to_json)
    if user_response.code == 200
      user_id = JSON.parse(user_response.body)['UserId']
    else
      # Handle the error
      user_id = nil
    end

    # Create the contact
    contact_payload = {
      "Function" => "CreateContact",
      "Parameters" => {
        "IsCompany" => false,
        "AssignedTo" => user_id,  #need to just get the USER ID so I can avoid doin the get call each time..
        "Name" => "#{self.name}",
        "Email" => "#{self.email}",
        "Phone" => "#{self.phone}",
        "Background Info" => "Originated from contact form on website",
      }
    }


    

    response = HTTParty.post(endpoint, headers: headers, body: contact_payload.to_json)
    contact_id = JSON.parse(response.body)['ContactId']
    
    # DO I REALLY NEED TO SAVE THIS INTO THE DB??
    #if response.code == 200
    #  # API Contact created successfully
    #  self.lacrm_contact_id = JSON.parse(response.body)['ContactId']
    #else
    #  self.lacrm_contact_id = 0
    #end
    #self.lacrm_response_code = response.code
    #self.lacrm_response_body = response.body

    

    # Add a note
    note_payload = {
      "Function" => "CreateNote",
      "Parameters" => {
    #    "ContactId" => "#{self.lacrm_contact_id}", #removed bc we're not saving that value into DB. 
        "ContactId" => contact_id,
        "Note" => "#{self.body}",
      }
    }
    HTTParty.post(endpoint, headers: headers, body: note_payload.to_json)

  end  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:create, :new, :confirmation, :location, :cfi, :home2]
  invisible_captcha only: [:create], honeypot: :confirm_email

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  def confirmation
  end

  def home2
    @message = Message.new
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end
  def location
    @message = Message.new
  end
  def cfi
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    #success = verify_recaptcha(action: 'message', minimum_score: 0.2, secret_key: ENV['RECAPTCHA_SECRET_KEY'])
    #checkbox_success = verify_recaptcha unless success

    respond_to do |format|
      if @message.save #&& (success || checkbox_success)
        MessageConfirmationMailer.message_confirmation_email(@message).deliver_later
        format.html { redirect_to contact_confirmation_path, notice: @message.body }
        #format.json { render :show, status: :created, location: @message }
      else
        format.html { 
          #if !success
          #  @show_checkbox_recaptcha = true
          #end
          render :new, status: :unprocessable_entity  }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  #def update
  #  success = verify_recaptcha(action: 'message', minimum_score: 0.3, secret_key: ENV['RECAPTCHA_SECRET_KEY'])
  #  checkbox_success = verify_recaptcha unless success
  #  
  #  respond_to do |format|
  #    if @message.update(message_params) && (success || checkbox_success)
  #      MessageMailer.new_message(@message).deliver
  #      format.html { redirect_to contact_confirmation_path, notice: @message.body }
  #      #format.json { render :show, status: :ok, location: @message }
  #    else
  #      format.html { 
  #        if !success
  #          @show_checkbox_recaptcha = true
  #        end
  #        render :new, status: :unprocessable_entity }
  #      format.json { render json: @message.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :email, :phone, :body)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, class: "font-thin") do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being sent:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-slate-200 outline-none px-3 py-2 mt-2 w-full focus:border-neutral-400 focus:ring-neutral-400" %>
  </div>

  <div class="my-5">
    <%= form.label :email, class: "" %>
    <%= form.email_field :email, class: "block shadow rounded-md border border-slate-200 outline-none px-3 py-2 mt-2 w-full focus:border-neutral-400 focus:ring-neutral-400" %>
  </div>

  <%= invisible_captcha :confirm_email, :message %>

  <div class="my-5">
    <%= form.label :phone, class: "" %>
    <%= form.text_field :phone, placeholder: "###-###-####", class: "placeholder:text-slate-300 block shadow rounded-md border border-slate-200 outline-none px-3 py-2 mt-2 w-full focus:border-neutral-400 focus:ring-neutral-400" %>
  </div>

  <div class="my-5">
    <%= form.label "YOUR MESSAGE", class: "uppercase" %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-slate-200 outline-none px-3 py-2 mt-2 w-full focus:border-neutral-400 focus:ring-neutral-400" %>
  </div>

  <%# if @show_checkbox_recaptcha %>
    <%#= recaptcha_tags %>
    <!--<div class="mb-10"></div>-->
  <%# else %>
    <%#= recaptcha_v3(action: 'message', site_key: ENV['RECAPTCHA_SITE_KEY']) %>
  <%# end %>

  <div class="inline">
    <%= form.submit "SEND MESSAGE", class: "btn-primary border border-white bg-red-600 hover:bg-red-500 text-xl text-white font-bold rounded-2xl" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= message.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= message.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= message.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= message.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this message", message, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this message', edit_message_path(message), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/messages/cfi.html.erb
<%# Head / Meta Data %>
<% title("Start Your Pilot Career | SimpliFly Flight School") %>
<% meta_description(" Join the team of instructors at Simplifly in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Share your passion for aviation and inspire future pilots as an instructor. Apply now.") %>
<% meta_keywords("Flight Instructor Position, CFI Job, Instruct at Simplifly, Mesa Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<%= render "shared/header"%>
<!--
<header class="w-full bg-gradient-to-r from-white to-sky-300  h-screen-3/4 lg:h-screen-4/5 flex justify-center items-center text-black">
  <div class="px-5 py-40 lg:py-52 flex flex-col justify-center items-center w-full">
      <h1 class="font-semibold font-header text-5xl lg:text-8xl lg:px-20 text-center">BE A CFI AT SIMPLIFLY</h1>
      <h2 class="font-bold text-xl lg:text-3xl italic text-center py-5 lg:py-10">How to become a CFI and gain experience</h2>
      <a href="#contact" class="btn-primary"
        onclick="event.preventDefault(); 
                const contactElement = document.getElementById('contact');
                const targetOffset = contactElement.offsetTop -20;
                window.scrollTo({ top: targetOffset, behavior: 'smooth' });">
        APPLY TODAY
      </a>
  </div>
</header>-->

<section class="bg-gradient-to-b from-slate-50 to-sky-200 flex flex-col items-center">
  <div class="max-w-4xl flex flex-col pt-10 px-5">
    <h3 class="text-5xl font-header uppercase font-semibold">Get Started on Your Pilot Career</h3>
    <h4 class="text-3xl text-slate-600 italic py-5">Simplifly Offers Accelerated and Flexible Training Options</h4>
    <p class="text-lg">Start your pilot career after getting your commercial certificate. Start flying now and build the necessary hours to become an airline pilot. One way SimpliFly can help is by becoming a certified flight instructor (CFI).  Being a CFI offers a valuable opportunity to rapidly accumulate flight experience for the minimum requirements of airlines and corporate aviation companies. It is a great opportunity that allows you to apply all the knowledge and skills acquired during your own flight training. Flight instructors play a crucial role as ambassadors of the aviation community, imparting their knowledge and experience to their students. For many, it serves as their first aviation job that not only is an invaluable experience but also provides compensation.</p>
    
    <h3 class="text-5xl font-header uppercase font-semibold pt-20 pb-5">How Long Will it Take?</h3>
    <p class="text-lg">Becoming a flight instructor does not have a minimum time, but you do need a commercial pilot license along with an instrument rating. To qualify for a commercial pilot license, a pilot must accumulate a minimum of 250 flight hours. That being said, if the minimum requirements are met it can take a little over a week to complete training if you are studying full time (accelerated).  If studying part time when able (flexible), it can take from a few weeks to a few months to be prepared for the CFI checkride and receive your endorsement.</p>

    <h3 class="text-5xl font-header uppercase font-semibold pt-20 pb-5">What are the Eligibility Requirements?</h3>
    <ul class="list-disc text-lg pl-10 lg:pl-16">
      <li>Be 18 years of age</li>
      <li>Read, speak, write and understand the English language</li>
      <li>Hold a commercial pilot certificate and an instrument rating</li>
      <li>Have logged at least 250 hours of flight time</li>
      <li>Hold a valid FAA 3rd Class Medical Cerificate (or higher)</li>
      <li>Receive a logbook endorsement from an authorized instructor on the fundamentals of instructing</li>
      <li>Pass a knowledge test on the aeronautical knowledge areas appropriate to the flight instructor rating sought</li>
    </ul>
    <p class="text-slate-600 italic pt-5">Reference 14 CFR §61.183 for the entire list of eligibility requirements.</p>

    <h3 class="text-5xl font-header uppercase font-semibold pt-20 pb-5">The SimpliFly Guarantee</h3>
    <p class="text-lg pb-20">If you have completed your <%= link_to "private", private_pilot_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, <%= link_to "instrument", instrument_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, <%= link_to "commercial", commercial_path, class: "text-sky-600 hover:underline", data: {turbo: false}%>, and CFI training at SimpliFly, we have an exciting opportunity for you. As a testament to our confidence in your abilities, we offer a guaranteed interview for a teaching position as a CFI within our flight school. This exclusive opportunity allows you to showcase the knowledge and skills you have acquired during your training journey with us. Join our team of dedicated instructors, inspire future aviators, and make a meaningful impact in the aviation community. Take the next step in your career as a CFI with SimpliFly and let your passion for aviation soar.</p>
  </div>
</section>


<section class="bg-gradient-to-l from-slate-200 to-blue-50"  id="contact">
  <h1 class="font-bold text-4xl pt-10 text-center">Instruct at SimpliFly</h1>
  <div class="lg:flex lg:flex-row-reverse items-center lg:items-start">
  

    <div class="mx-10 lg:px-16 lg:w-1/2">
      <%= render "form", message: @message %>      
    </div>

    <div class="mx-0 lg:w-1/2">
      <%=image_tag "simplifly-team.webp", class: "lg:pt-10", alt: ""%>
    </div>

  </div>
</section>


<%= render "shared/footer"%>

app/views/messages/confirmation.html.erb
<%# Head / Meta Data %>
<% title("Confirmation Details| Pitcairn Aviation LLC") %>
<% meta_description("Make Pitcairn FBO your aviation home. Contact us today to explore our full-scale services, expert support, and client-centered approach to flight needs") %>
<% meta_keywords("Pitcairn FBO, aviation home, contact us, flight needs, full-scale services, expert support, client-centered approach, aviation services, flight plans, representative support") %>

      
<%= render "shared/header" %>

<section class="mt-5">

<div class="relative mx-auto max-w-xl  rounded-lg bg-gradient-to-tr from-pink-300 to-blue-300 p-0.5 shadow-lg">
    <div class="bg-white p-7 rounded-md">
        <h1 class="font-bold text-xl mb-2">Thank you for contacting Pitcairn Aviation LLC. </h1>
        <p ">------------</p>
                        <p >We are looking forward to working with you soon.  We will review your message and get back with you within 1-5 business days.  <br><br>
                        You can also give us a call at <%=link_to "(610) 495-7000", "tel:1-610-495-7000" %> or email us at <%= mail_to 'info@pitcairnaviation.com', class: "text-slate-800 hover:underline"%></p>
    </div>
</div>

</section>

app/views/messages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Messages</h1>
    <%= link_to 'New message', new_message_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="messages" class="min-w-full">
    <%= render @messages %>
  </div>
</div>

app/views/messages/location.html.erb
<%# Head / Meta Data %>
<% title("Visit Us | SimpliFly Flight School") %>
<% meta_description("Visit Simplifly, the top-rated flight school in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Experience our state-of-the-art facilities and meet our instructors. Schedule your visit today.") %>
<% meta_keywords("Visit Simplifly, Flight School Visit, Mesa Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<%= render "shared/header"%>

<header class="w-full bg-canyon bg-cover h-screen-3/4 lg:h-screen-4/5 flex justify-center items-center text-white">
  <div class="px-5 py-40 lg:py-52 flex flex-col justify-center items-center w-full">
      <h1 class="font-semibold font-header text-5xl lg:text-8xl lg:px-20 text-center">CHECK SIMPLIFLY OUT</h1>
      <h2 class="font-bold text-xl lg:text-3xl italic text-center py-5 lg:py-10">We're at Falcon Field and Spanish Fork</h2>
      <a href="#contact" class="btn-primary"
        onclick="event.preventDefault(); 
                const contactElement = document.getElementById('contact');
                const targetOffset = contactElement.offsetTop -20;
                window.scrollTo({ top: targetOffset, behavior: 'smooth' });">
        CONTACT US
      </a>
  </div>
</header>

<%= render "shared/visit_school"%>

<div class="bg-gradient-to-l from-slate-200 to-blue-50"  id="contact">
  <h1 class="font-bold text-4xl pt-10 text-center">Contact Us</h1>
  <div class="lg:flex lg:flex-row-reverse items-center lg:items-start">
  

    <div class="mx-10 lg:px-16 lg:w-1/2">
      <%= render "form", message: @message %>      
    </div>

    <div class="mx-0 lg:w-1/2">
      <%=image_tag "simplifly-team.webp", class: "lg:pt-10", alt: ""%>
    </div>

  </div>

</div>


<%= render "shared/footer"%>

app/views/messages/newbck.html.erb
<%# Head / Meta Data %>
<% title("Contact Us | SimpliFly Flight School") %>
<% meta_description("Contact Simplifly, the premier flight school in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Reach out to us for inquiries, information, or to schedule a visit. We're here to assist you.") %>
<% meta_keywords("Contact Simplifly, Flight School Contact, Mesa Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<%= render "shared/header"%>
<div class="bg-gradient-to-l from-slate-200 to-blue-50">
  <h1 class="font-bold text-4xl pt-10 text-center">Contact Us</h1>
  <div class="lg:flex lg:flex-row-reverse items-center lg:items-start">
  

    <div class="mx-10 lg:px-16 lg:w-1/2">
      <%= render "form", message: @message %>      
    </div>

    <div class="mx-0 lg:w-1/2">
    
    </div>

  </div>

</div>

<%= render "shared/footer"%>

app/views/messages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @message %>

    <%= link_to 'Edit this message', edit_message_path(@message), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this message', message_path(@message), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/messages/simplifly-confirmation.html.erb
<%= render "shared/header" %>
<main class="bg-slate-50 w-full flex flex-col items-center justify-center">
  <!--Container for contents-->
  <div class="text-center lg:w-3/5 md:w-4/5">
    
    <h1 class="font-bold text-4xl py-10">Your message has been sent!</h1>
    
    <!--Container for check-->
    <div class="flex flex-row justify-center">
      <!--circle of check-->
      <div class="bg-blue-200 rounded-full py-3 px-4 mb-10">
        <!--check itself-->
        <div class="text-sky-500 text-5xl">✓</div>
      </div>
    </div>
    
    
    <%#-- The message (lol, i used a "notice" to bring the message data to this page hahahaha) --%>
    <% if notice.present?%>
    <p class="font-semibold">Your Message:</p>
    <div class="mb-5 px-5 italic text-gray-500 text-sm">
      <%= notice %>
      </div>
    <% end %>
  
    
    <p class="px-5 p-text">
    Thank you for contacting SimpliFly.  We are looking forward to working with you soon.  We will review your message and get back with you within 1-5 business days.  <br><br>
    You can also give us a call at <%=link_to "1-480-256-8355", "tel:1-480-256-8355" %> or email us at <%= mail_to 'info@simpliflyco.com', class: "text-slate-800 hover:underline"%>
    </p>

    <div class="pt-10 flex flex-row justify-center">
    <%= link_to root_path do %>
      <div class="btn-primary mb-10 w-52">
        HOME
      </div>
    <% end %>
    </div>
    

    <%#= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</main>

<%= render "shared/footer"%>